### ISSUE TITLE
Mod Loader 2016 Clinton

### ISSUE THREAD

**Issue by riccardobenassi** [newcampaigntrail/newcampaigntrail.github.io#100]
The 5 Mods set in 2016 with Clinton (Manchin, McCaskill, Castro, Tester, Gore) all load the standard 2020 model

**Comment by Danxv33** [comment]
Click through to the game and ignore that (Just choose Kaine), then open the map and close the map. does it load then?

**Comment by newcampaigntrail** [comment]
Closed because these mods have been temporarily benched.
