### ISSUE TITLE
adding link to newcampaigntrail

### ISSUE THREAD

**Issue by theclosedbitter** [newcampaigntrail/newcampaigntrail.github.io#133]
add the link to the website in description and website thing on github

**Comment by Danxv33** [comment]
Added the link to the Readme file, so I guess we're done here?

**Comment by theclosedbitter** [comment]
NO we are not I meant adding it to the website description like this  
![Screenshot 2022-12-13 at 02-08-22 SHSGames_shsgames github io Unblocked Games](https://user-images.githubusercontent.com/117611091/207208667-59af16e9-d2dc-4586-8b97-1c0e1907b864.png)
