### ISSUE TITLE
Several mod scenarios broken, stuck at processing results

### ISSUE THREAD

**Issue by Wolf-in-the-Mask** [newcampaigntrail/newcampaigntrail.github.io#138]
Starting with today, several mod loader scenarios get stuck at "Processing Results, wait one moment..." once answering the final question. 

The affected scenarios I was able to find were:
- 1880
- 1992
- 1996b
- 2000b
- 2008!
- 2008c

This list is not exhaustive, as it seems that many more that can be affected. To reproduce this bug, all you have to do is play one of these scenarios to the end, and instead of seeing the results, you'll only get the endless "Processing Results, wait one moment..." message instead.

Also, these scenarios actually DO work if loaded manually (by finding Code 1 and Code 2 for them on Reddit and posting them myself), but when launching these from the mod loader, they're broken like that.

**Comment by BD480** [comment]
1996MN
1836TX
Also affected

**Comment by Fish1** [comment]
Hello!

**Comment by BD480** [comment]
Hello there

**Comment by BD480** [comment]
3 New ones today
1936
1936C
1992

**Comment by BD480** [comment]
All fixed except encountered the error on 1996 as Perot

**Comment by Wolf-in-the-Mask** [comment]
I once again commend the devs for fixing this, and reworking the mod loader too! This issue is thus resolved <3
