### ISSUE TITLE
reopen @134

### ISSUE THREAD

**Issue by theclosedbitter** [newcampaigntrail/newcampaigntrail.github.io#141]
I meant this not adding it to the README
EXAMPLE
![Screenshot 2022-12-13 at 02-08-22 SHSGames_shsgames github io Unblocked Games](https://user-images.githubusercontent.com/117611091/207208875-5e7cae6c-e079-4ae0-9d65-8683c0b99b4c.png)

**Comment by newcampaigntrail** [comment]
More info needed. Can you clarify what you mean?

**Comment by JetSimon** [comment]
They mean adding the link to game to the "about" tab on the right. I think you can do it in the repo settings.

**Comment by newcampaigntrail** [comment]
Done.
