### ISSUE TITLE
1912 Election as Taft

### ISSUE THREAD

**Issue by MichaelW96** [newcampaigntrail/newcampaigntrail.github.io#142]
Hello, when I pick the 1912 election in the mod loader and choose Taft with any running mate, I end up with the Bush/Cheney election with respective options. On the map it shows percentages for Taft and Wilson, when I go back to the game I have Bush and Cheney again.

**Comment by newcampaigntrail** [comment]
The 1912 election never had a Taft playable candidate. Unfortunately it was never made.

If it is ever updated with Taft it will for sure be added to the mod loader.
