### ISSUE TITLE
1972 (Nixon vs McGovern)

### ISSUE THREAD

**Issue by ablfar** [newcampaigntrail/newcampaigntrail.github.io#145]
I started playing this mod, and it says that I am playing as Ford/Dole, and assumes Carter is my opponent in one of the questions. So I think this was accidentally made as the 1976 election instead

**Comment by cooguy8** [comment]
This is because only the McGovern side is finished at the moment. This shows up because you chose the Nixon side

**Comment by Danxv33** [comment]
The previous commenter is correct. Closing issue.
