### ISSUE TITLE
Many scenarios do not progress to the final result

### ISSUE THREAD

**Issue by PeterLeeofKor** [newcampaigntrail/newcampaigntrail.github.io#146]
As of yesterday (01/02/2023 at GMT+9), many mod loader scenarios and regular scenarios say "Processing Results, wait one moment..." when pressing the 'go to final result' button.  And the final results page doesn't load.  Scenarios I checked today (01/03/2023 at GMT+9);  1988, 2020, 1796, 1844, 1860, 1852, 1880, 1988b, 1980... This will probably be observed in all running scenarios.  please help!

**Comment by newcampaigntrail** [comment]
I can't recreate this. You need to state your platform etc.

**Comment by Danxv33** [comment]
Did you clear your cache?

**Comment by PeterLeeofKor** [comment]
> 



> I can't recreate this. You need to state your platform etc.

Samsung Galaxy 10 mobile and Samsung Galaxy Book laptop. Both sides accessed via Google Chrome.

**Comment by newcampaigntrail** [comment]
Resolved iirc.
