### ISSUE TITLE
I can't see any more endings of the game in any scenario

### ISSUE THREAD

**Issue by felipeaguia** [newcampaigntrail/newcampaigntrail.github.io#160]
Basically, the problem is that I can play the scenario normally but when showing the ending, when showing the ending it shows quickly (like 1 second) and goes back to the initial Campaign Trail screen (that is, there is no time to read the ending), I've been dealing with this problem for a long time (since before these ending codes existed), and at first I could see the endings but since the number of mods increased I can't see the endings anymore and I don't know why, I I'm from a non-English speaking country so I don't know if it's the distance that's affecting or creating a bug, but it's frustrating not being able to see the endings anymore.

**Comment by felipeaguia** [comment]
And yes, I've already tried switching browsers, from Chrome to Mozilla and Edge and the problem remains regardless of the browser.

**Comment by ItsAstronomical** [comment]
I'm very sorry to hear about this. If you don't mind, could you tell us what language and/or time/date notation your country uses? I know a while back we had a similar bug with those playing on computers set to the Korean language, and it was due to the way time is written on computers in their country.

**Comment by felipeaguia** [comment]
Oh,Hi,sorry I just have time to see this now,I speak from Brazil, in South
America, if I'm not mistaken and if I understood your question correctly,
the time difference is 2 hours more or less, or GMT-3, however I played the
game using Google Translate because that the game does not have an official
translation for my language, I don't know if there are more people in my
country or South America who play the game with the same problem, but I
hope you guys manage to solve it, again sorry for the delay in the
response, I just went look at my email today.

Em seg., 20 de mar. de 2023 às 21:15, Astronomical ***@***.***>
escreveu:

**Comment by felipeaguia** [comment]
Oh and I speak Brazilian Portuguese.

Em qua., 22 de mar. de 2023 às 20:37, Felipe Goncalves Aguiar <
***@***.***> escreveu:

**Comment by ItsAstronomical** [comment]
I don't know any other South American players, but I will see if I can do more research on this. Are you playing on Windows?

**Comment by newcampaigntrail** [comment]
I *think* this was resolved.
