### ISSUE TITLE
Not Because It Is Hard, But Because It Is Easy - Achievement is broken!

### ISSUE THREAD

**Issue by th3birdman333** [newcampaigntrail/newcampaigntrail.github.io#164]
I've done this achievement like 5 times on cakewalk (as it states is required) and have not had this trigger for me yet.

**Comment by ItsAstronomical** [comment]
That is weird. Any more info on the device/operating system you're playing on?

**Comment by th3birdman333** [comment]
Hey sorry for the delay.  You can totally disregard this.  The achievement did pop I just... Didn't realize the picture was in back and white so thought the achievement wasn't unlocked. XD, My bad!  (Had sound muted and checked inspect Element and I do have that achievement.)
