### ISSUE TITLE
Achievement's lost

### ISSUE THREAD

**Issue by th3birdman333** [newcampaigntrail/newcampaigntrail.github.io#192]
Hey, I know there was a mistake on the devs end here, or so I'm told, when they switched websites.  I was also told they could help recover the achievements especially the really hard ones for some people.  I would like to make a request if possible to have my achievements restored as I had all of them except for one (the JFK impossible difficulty one).  I would be eternally grateful if you could help me recover these!  If it takes some times that's alright, no worries.  Thank you for the help in advance.  🙏

Some other info:  I play on mobile (android, LG G8) and use Chrome as my browser.

**Comment by newcampaigntrail** [comment]
It was a part of the domain switch. We explained more on the [devlog](https://blog.newcampaigntrail.com/).

**Comment by th3birdman333** [comment]
I'm fully aware, but I was told by someone on reddit (DecStar) they would be able to look into restoring AT LEAST some of the harder achievements if needed, so I would like to pursue that option kindly, please.
