### ISSUE TITLE
Reopening ticket #192

### ISSUE THREAD

**Issue by th3birdman333** [newcampaigntrail/newcampaigntrail.github.io#194]
I'm fully aware, but I was told by someone on reddit (DecStar) they would be able to look into restoring AT LEAST some of the harder achievements if needed, so I would like to pursue that option kindly, please.

_Originally posted by @th3birdman333 in https://github.com/newcampaigntrail/newcampaigntrail.github.io/issues/192#issuecomment-1550650368_
           

Additionally the memo thing you linked says this:

> If you desperately need certain achievements back, you can contact a dev, and we can have a look into what we can do (in the case of extremely hard-to-get achievements, such as the JFK or 2016a one).

I had many extremely hard to get achievements, so I would like to pursue this, or get in touch with a dev that can help me restore at least the hardest ones.

**Comment by th3birdman333** [comment]
I understand this is mostly a client side thing, just tell me what I need to do or give you, or give me a devs info (I only know of decstar and prefer not to bother him) and I can chat with them on reddit or discord or whereever.  

Thanks.

**Comment by Danxv33** [comment]
Go on the TNCT discord. Message the person with my name.
