### ISSUE TITLE
Uk 2017: Thatcherite Conservative fails to iniatialize

### ISSUE THREAD

**Issue by Washingwithgeorge** [newcampaigntrail/newcampaigntrail.github.io#251]
The 2017 UK mod only loads Trump 2020 when selecting the Thatcherite strategy. It doesn't matter if I'm on PC, or mobile the same thing happens.
![Screenshot_20230821_221551_Samsung Internet](https://github.com/newcampaigntrail/newcampaigntrail.github.io/assets/142858423/6598c861-f8a3-4463-8e9c-c58da88935dd)
![Screenshot_20230821_221653_Samsung Internet](https://github.com/newcampaigntrail/newcampaigntrail.github.io/assets/142858423/efdabfa2-d19e-4a25-8c30-6a3208b30c61)

**Comment by ItsAstronomical** [comment]
Odd. It works fine on my PC, although it does take a visible second for the site to refresh. What browser/OS for your computer are you using?

**Comment by Washingwithgeorge** [comment]
This was before you fixed the file. Thanks.
