### ISSUE TITLE
Don't use discord as a filehost

### ISSUE THREAD

**Issue by Fish1** [newcampaigntrail/newcampaigntrail.github.io#264]
Discord isn't a file host, and they are going to make changes to prevent it from happening.

![image](https://github.com/newcampaigntrail/newcampaigntrail.github.io/assets/13600696/12a5f29d-d9c8-4ba8-8539-157327a99206)

**Comment by ItsAstronomical** [comment]
I waited to close this issue until Discord made the switch. All modders were given advanced notice.
