### ISSUE TITLE
Happy Warrior Hotfix Pull Request Thingy

### ISSUE THREAD

**Issue by WNDIUA** [newcampaigntrail/newcampaigntrail.github.io#291]
New Mod Icon: https://i.imgur.com/F7n5aSP.png

New Code 1: https://gist.githubusercontent.com/WNDIUA/20ffd6e1b8ea84189d0e181592089566/raw/7abb6e97347dc78f36100c9db0ba7a1f541a2dd4/Code%25201

New Code 2 for Askew: https://gist.githubusercontent.com/WNDIUA/ae9846009f98e22dd48881daabfa927d/raw/8e8407a144d3df0e281220ddd20886c83652c3f0/Code%25202%2520for%2520Askew

New Code 2 for Dukakis: https://gist.githubusercontent.com/WNDIUA/142616948b85a86eec78b96a25d88cc7/raw/d75014af98923dace634d1301381e41e218a82b9/Code%25202%2520for%2520Dukakis

Thanks.

**Comment by ItsAstronomical** [comment]
Oops, sorry I did not see this until now.
