### ISSUE TITLE
Campaigns not loading

### ISSUE THREAD

**Issue by chipm123** [newcampaigntrail/newcampaigntrail.github.io#317]
Campaigns not loading
<img width="1440" alt="Screenshot 2024-02-25 at 3 34 21 PM" src="https://github.com/newcampaigntrail/newcampaigntrail.github.io/assets/153100732/4dd2c50a-8e16-42f1-afaa-e9e5930958c6">

**Comment by ItsAstronomical** [comment]
This has been fixed awhile ago.
