### ISSUE TITLE
Audio is not playing.

### ISSUE THREAD

**Issue by Brenthoven** [newcampaigntrail/newcampaigntrail.github.io#319]
No matter the amount of times I try to play the audio on any of the Mods. It doesn't want to work. I've tried on the following mods:

- Midnight65
- Midnight64
- Red 1948

And even when I hit "Play", it doesn't still work.

**Comment by EnvironmentalCap104** [comment]
It's because they've shared their audio through Discord, and Discord has stopped photo/audio sharing. They just haven't changed the links on their music to other sites, like Jukehost (I think that's what it's called).

**Comment by Brenthoven** [comment]
Slight note: I was banned from the Server... so idk if that has to do with that.

**Comment by ItsAstronomical** [comment]
No, that has nothing to do with it. EnvironmentalCap104 is correct. 

This is an issue for individual modders to solve. They were given notice many months in advance about Discord making it so you cannot host files through it.
