### ISSUE TITLE
Can't play as Eugene Debs in 1912

### ISSUE THREAD

**Issue by kkerasounlis** [newcampaigntrail/newcampaigntrail.github.io#354]
Game crashes immediately the moment you click to begin as Debs after difficulty selection.

It says candidate not found.

**Comment by ItsAstronomical** [comment]
There is no Debs side to the current 1912 mod.

**Comment by kkerasounlis** [comment]
https://github.com/newcampaigntrail/newcampaigntrail.github.io/assets/29676295/45a97502-c6cb-4ef2-9e08-e90484087d22

Then what is this

**Comment by ItsAstronomical** [comment]
Sorry I am late, but that is just the Code 1. The modmaker never created a Debs code 2.
