### ISSUE TITLE
code 1 updated for 1988 rainbow trail

### ISSUE THREAD

**Issue by WNDIUA** [newcampaigntrail/newcampaigntrail.github.io#385]
https://gist.githubusercontent.com/WNDIUA/85ee18f7c06aea7d4dbf01eda80c2134/raw/7ebcf6d96fd9c1429ba2d593bcb1da1275c35d8f/Code%25201%2520Rainbow%2520Trail%2520V2

thanks astro

**Comment by ItsAstronomical** [comment]
sorry I missed this
