### ISSUE TITLE
2024 Democracy's Martyrdom

### ISSUE THREAD

**Issue by cael73** [newcampaigntrail/newcampaigntrail.github.io#386]
Neither path you can take is able to be completed in Democracy's Martyrdom, it stops progressing in different spots though. If you run for president in freezes near the end and about halfway through if you don't

**Comment by ItsAstronomical** [comment]
A patch has been released for the mod. Do the bugs still occur?

**Comment by cael73** [comment]
No they don’t, it’s fixed now thank you

On Dec 1, 2024, at 6:04 PM, Astronomical ***@***.***> wrote:

﻿

A patch has been released for the mod. Do the bugs still occur?
